### ISSUE TITLE
Why do we need an "absolute path" for the solverdummy?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/matlab-bindings#18]
The solverdummy's [README](https://github.com/precice/matlab-bindings/blob/6cf1d01e4732eebf22789998fee9834b4eb2a530/solverdummy/README.md) provides the following note:

---
Please note: Currently, the MATLAB solverdummy can't be coupled with other solvers unless an exchange directory is specified with its **absolute path** in the config file. So, if you wish to couple with a different solver, please make sure to modify the config file accordingly.

---

Why do we require an **absolute path**? We should check this example. Either this is an error in the documentation or there is a bug. Usually no exchange directory is required, if the solverdummies are started from the same folder. If the solverdummies are started from different folders, the exchange directory has to be specified, but also a relative path (e.g. `..`) is allowed.

**Comment by BenjaminRueth** [comment]
Note that, for example, in the [solverdummy config](https://github.com/precice/matlab-bindings/blob/develop/solverdummy/precice-config.xml) no absolute path (something like `<m2n:sockets exchange-directory=ABSOLUTE_PATH/>`) is provided and the example works. Therefore, this might be a documentation issue and everything in the code seems fine.

**Comment by erikscheurer** [comment]
> Therefore, this might be a documentation issue and everything in the code seems fine.

I agree with you, I was able to couple the cpp solverdummy fine with exchange directory `".."`.  Other directories like `"../test"` worked also without a problem.
