### ISSUE TITLE
Add version information to repository/code

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/matlab-bindings#24]
As far as I understand the code and repository do not say anything about the current version of the bindings. There are, of course, [tags](https://github.com/precice/matlab-bindings/tags) and [releases](https://github.com/precice/matlab-bindings/releases), but if we are only looking at the code it has no version. This becomes obvious in https://github.com/precice/matlab-bindings/pull/23, where a release PR is created by no files are changed.

Is there a convention on how to provide the version of a MATLAB package?

**Comment by BenjaminRueth** [comment]
From https://github.com/precice/matlab-bindings/pull/23#issuecomment-707608393:

> I am not sure how we can end up in a situation where a release has no commits.

@fsimonis I think the current situation is mainly a symptom of this issue. I would suggest to track the version in any kind of sane way for the matlab bindings. For the python bindings we cannot get into this situation: there will always be a "bump version" commit.

**Comment by BenjaminRueth** [comment]
I looks like MATLAB offers a versioning mechanism: https://de.mathworks.com/help/matlab/ref/ver.html. This seems the correct way to go.

**Comment by IshaanDesai** [comment]
The appropriate way to add version information is to create a [Contents.m](https://de.mathworks.com/help/matlab/matlab_prog/create-a-help-summary-contents-m.html) and then specify the `Version` as a comment in that file. 
* Additionally this file can contain information regarding files and functionality in the particular folder. This information is printed when the user writes `help <package-name>`
