### ISSUE TITLE
n x d vs. d x n ordering of vector valued data

### ISSUE THREAD

**Issue by BenjaminRueth** [precice/matlab-bindings#4]
Old discussion (https://github.com/precice/precice/issues/458), but now for the MATLAB bindings.

Which format should we follow?

* `n x d`, since this would be consistent with what we are doing in the python bindings?
* `d x n`, for other reasons? (maybe Fortran ordering is more common in MATLAB?)

**Comment by BenjaminRueth** [comment]
We do not have to hurry on this issue, but make sure to come to a reasonable decision before the release.

**Comment by BenjaminRueth** [comment]
We should also make sure to add some security checks on user input. See [here](https://github.com/precice/python-bindings/blob/3b9aec6c529814e6904a6a4697cf92388d4c4bf0/precice.pyx#L130-L139).

**Comment by gilbertolem** [comment]
In terms of user usage, I have seen that using `n x d` or `d x n` is a heavily personal choice. However, MATLAB stores its arrays in column-major order (FORTRAN-like). As such, keeping the `d x n` convention would save some memory-management steps in the interface with preCICE. 

We could try keeping it as `d x n` and see if there is some feedback or comments from users.

**Comment by gilbertolem** [comment]
> We should also make sure to add some security checks on user input. See [here](https://github.com/precice/python-bindings/blob/3b9aec6c529814e6904a6a4697cf92388d4c4bf0/precice.pyx#L130-L139).

I added the security checks in #14.

**Comment by BenjaminRueth** [comment]
> However, MATLAB stores its arrays in column-major order (FORTRAN-like).

This sounds like we have a reasonable convention for MATLAB. Since #14 implements the checks, we also enforce this convention in our bindings. This closes the issue.
